

services:
  postgres-db:
    image: postgres:15
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=helloworld
      - POSTGRES_DB=renel-db
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - renel-network
    env_file:
      - .env

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: nest-api
    ports:
      - "3000:3000"
    depends_on:
      - postgres-db
    networks:
      - renel-network
    environment:
      - DATABASE_URL=postgresql://admin:helloworld@postgres-db:5432/renel-db?schema=public
    command: sh -c "npx prisma migrate deploy && npm run start:dev"
  

volumes:
  postgres-db:
  
networks:
  renel-network:
    driver: bridge
