version: '3.3'

services:
  app:
    container_name: nest-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - postgres-db
    networks:
      - renel-network
    env_file:
      - .env

  postgres-db:
    image: postgres:13
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=helloworld
      - POSTGRES_DB=renel-db
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - renel-network
    env_file:
      - .env

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=helloworld
    depends_on:
      - postgres-db
    networks:
      - renel-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-db:
  pgadmin-data:

networks:
  renel-network:
    driver: bridge
