name: Nodejs CD to VPS

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOST}}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}    
        passphrase: ${{ secrets.PASSPHRASE }}
        port: 22
        script: |
            cd /home/steven/smart-iot
            git pull origin main
            git status
            npm i --only=prod
            pm2 restart main
