name: Deploy to VPS
run-name: On a new commit, deploy the code to production server

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Uses Nodejs 18
      uses: actions/setup-node@v2
      with:
        node-version: 18.x
    - run: npm i
    - run: npm run build --if-present
    - run: npm test
      
